public class Social_ConsumerReportConstants{

   public static Set<Id> consumerRecordTypeSet = new Set<Id>{'012E0000000csej','012E0000000csel','012E0000000csek','012L00000000IAZ'};
   public static Set<String> productDSLSet = new Set<String>{'Email','DSL','WiFi'};
   public static Set<String> productUverseSet = new Set<String>{'Dish / Direct TV / Satellite','U-verse'};
   public static Set<String> productYellowPagesSet = new Set<String>{'Yellow Pages'};
   public static Set<String> productLandlineSet = new Set<String>{'Landline'};
   public static Set<String> productOthersSet = new Set<String>{'Unknown','Digital Life','Non Actionable'};


}