/**************************************************************************
Trigger Name: social_caseCounterUserUpdateConstants
Author: Accenture
Requirement/Project Name: Social Consumer 
Description: class will hold the string used in social_caseCounterUserUpdate class.
Version History: Aditya(24/April/2014) - Release 19March2014
**************************************************************************************************************************/

Public class social_caseCounterUserUpdateConstants {
    public static final string STATUS_NEW = 'New';
    public static final string STATUS_REOPEN = 'Reopen';
    public static final string STATUS_REASSIGNED = 'Reassigned';
    public static final string STATUS_INVESTIGATING = 'Investigating';
    public static final string STATUS_ESCALATED = 'Escalated';
    public static final string STATUS_FOLLOW_UP_HOLD = 'Follow Up Hold';
    public static final string STATUS_CLOSED = 'Closed';
    public static final string USER_ID = '005';
    public static final string QUEUE_ID = '00G';
}