@isTest(Seealldata = false)
public class social_ReportsControllerTest {
     /*
         Test class for AvgCMResponseTimeFromAssignment controller
     */
     public static TestMethod void AvgCMResponseTimeFromAssignmentTest() {
         AvgCMResponseTimeFromAssignment avgClass = new AvgCMResponseTimeFromAssignment();
         avgClass.getData();
     }
     
     /*
         Test class for firstCustResponse
     
     
     public static TestMethod void firstCustResponseTest() {
         firstCustResponse firstCustClass = new firstCustResponse();
         firstCustClass.getData();
     }*/
}